# Generated by Django 5.1.4 on 2024-12-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Primera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('año', models.PositiveIntegerField()),
                ('duracion', models.DurationField()),
                ('canciones', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='discos_imagenes/')),
                ('sello', models.CharField(max_length=100)),
            ],
        ),
    ]
